// ---------------------------------------------------------------------------------
// example4.c
//
// Read in the output file generated by example1.c
// Graphically show the relationship between the IP addresses, countrys and ASNs.
//
// 1. Set the input file to be ../output_data/output1.csv
// 2. Set the graphics output file to be ../output_data/output4.dot and use the
//    "twopi" rendering algorythm.
// 3. Colour the country node red.
// 4. Draw the relationship between the fields source_ip, ASN and country using
//    the draw_path function instead of several draw_node calls. 
//
// --------------------------------------------------------------------------------

#include "../src/externs.h"
void setup() {
	set_input(' ',"../output_data/output1.csv");
	set_graphics("../output_data/output4.dot","twopi");
}
void loop() {
	add_country("source_ip"); add_asn("source_ip");
	add_label("source_ip", "name *");
	add_attributes("source_ip.country","color=red");
	draw_path("source_ip,source_ip.asn,source_ip.country");
}
