.\" WR - 2018"

.TH ADD_ASN 3  2018-08-08 "DAPL" "DAPL Programmer's Manual"
.SH NAME
add_asn - Using an IP address field, Add an ASN field
.SH SYNOPSIS
.nf
.B #include externs.h
.sp
.BI "void add_asn(char " "*IP_ADDRESS_FIELDNAME" );
.fi
.SH DESCRIPTION
.sp
The
.BR add_asn ()
function tests to see if the current record contains a field 
.BR _DROP 
with a positive value. If the result is positive, then 
.BR add_asn() 
returns without performing any function.
A test is then performed to see if IP_ADDRESS_FIELDNAME exists in the current record structure.
If the field is found, then the IP_ADDRESS_FIELDNAME value is extracted from the record and is 
searched for in the file set by the bash variable $ASN_FILE. If the address is found, 
the ASN value associated with it is inserted into the record structure as fieldname 
IP_ADDRESS_FIELDNAME.asn.
.fi
.SH USAGE:
Loop code block only.
.fi
.SH RETURN VALUE: 
add_asn () returns void.
.fi
.SH SEE ALSO:
add_country 
.SH BUGS:
No known bugs.
.SH AUTHOR:
WR
