#!/bin/bash
URL=$(echo "GET /check/$1 HTTP/1.0\\r\\nHost: www.abuseipdb.com\\r\\n\\r\\n")
filter () {
COUNTER=0
while read LINE; do
	COUNTER=$[$COUNTER +1]
	if [ $COUNTER -eq 24 ]; then 
		STR1=$(echo $LINE | sed 's/<title>//g; s/<\/title>//g; s/|//g; s/AbuseIPDB//g')
	fi
	if [ $COUNTER -eq 25 ]; then
		COUNTER1=0;
		for WORD in $LINE; do 
			COUNTER1=$[$COUNTER1 +1]
			if [ $COUNTER1 -eq 7 ]; then
				if [ $WORD == "reported.\"/>" ]; then 
					CTR="0"
				else 
					CTR=${WORD}
				fi
			fi
		done;
	fi
done
	echo $STR1,count=$CTR
}
sslcat -h www.abuseipdb.com -u "${URL}" | filter 
