#!/bin/bash
if [ "$(id -u)" != 0 ]; then
	echo "This script must be run as root"
	exit 0
fi
# Ensure local bin and sbin directories are present - If not then make them
mkdir -p /usr/local/bin
mkdir -p /usr/local/sbin
# Check standard distribution packages are installed

	if ! rpm -qa | grep -qw openssl-devel; then
 		echo Package Openssl-dev - Not installed
    		dnf install openssl-devel
	else echo Package Openssl-devel Ok
	fi
	if ! rpm -qa | grep -qw clang; then
		echo Package clang - Not installed
		dnf install clang
	else echo Package clang - Ok 
	fi
	if ! rpm -qa | grep -qw graphviz; then
		echo Packasge graphviz - Not installed
		dnf install graphviz
	else echo Package graphviz - Ok
	fi
	if ! rpm -qa | grep -qw detox; then 
		echo Package detox - Not installed
		dnf install detox
	else echo Package detox - Ok
	fi
	if ! rpm -qa | grep -qw dos2unix; then
		echo Package dos2unix - Not installed
		dnf install dos2unix
	else echo Package dos2unix - Ok
	fi
	if ! rpm -qa | grep -qw perl-CPAN; then
		echo Package perl-CPAN - Not installed
		dnf install perl-CPAN
	else echo Package perl-CPAN - Ok
	fi
	
# Check non-standard packages are installed
file="/usr/local/bin/msgconvert"
if [ ! -f "$file" ]; then
	echo Perl script msgconvert - Not installed
 	rm -rf MSG-Convert
 	perl -MCPAN -e 'install("Email::Outlook::Message")'
 	perl -MCPAN -e 'install("Email::LocalDelivery")'
 	perl -MCPAN -e 'install("Getopt::Long")'
 	perl -MCPAN -e 'install("Pod::Usage")'
 	perl -MCPAN -e 'install("File::Basename")'
 	git clone https://github.com/craig552uk/MSG-Convert.git
 	mv MSG-Convert/msgconvert.pl /usr/local/bin/msgconvert
 	rm -rf MSG-Convert
else echo Perl script msgconvert - Ok	
fi

