#!/bin/bash
if [ "$(id -u)" != 0 ]; then
	echo "This script must be run as root"
	exit 0
fi
	if ! rpm -qa | grep -qw openssl-devel; then
 		echo Package Openssl-dev - Not installed
    		dnf install openssl-devel
	else echo Package Openssl-devel Ok
	fi
	if ! rpm -qa | grep -qw clang; then
		echo Package clang - Not installed
		dnf install clang
	else echo Package clang - Ok 
	fi
	if ! rpm -qa | grep -qw graphviz; then
		echo Packasge graphviz - Not installed
		dnf install graphviz
	else echo Package graphviz - Ok
	fi
file="/usr/local/bin/msgconvert"
if [ ! -f "$file" ]; then
	mkdir -p /usr/local/bin
 	rm -rf MSG-Convert
 	perl -MCPAN -e 'install("Email::Outlook::Message")'
 	perl -MCPAN -e 'install("Email::LocalDelivery")'
 	perl -MCPAN -e 'install("Getopt::Long")'
 	perl -MCPAN -e 'install("Pod::Usage")'
 	perl -MCPAN -e 'install("File::Basename")'
 	git clone https://github.com/craig552uk/MSG-Convert.git
 	mv MSG-Convert/msgconvert.pl /usr/local/bin/msgconvert
 	rm -rf MSG-Convert
fi

