#!/bin/bash
cpu_count=$(grep -c ^processor /proc/cpuinfo)
export LC_ALL=C
pid_array=( 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 )
trap "exitfn" INT
exitfn () {
    let count=0
    echo;echo **Ignored**
    echo
}
let count=0
for files in $DNS_REG/*; do
        let spawn=0
        while [ $spawn -eq 0 ]; do
                while [ $count -lt $cpu_count ]; do
                        if [ ${pid_array[$count]} -eq 0 ]; then
                                taskset -c $count zgrep --line-buffered $1 $files &  
                                pid_array[$count]=$!
                                let spawn=1
                                break
                        fi
                        let count=count+1
                done
                if [ $spawn -eq 0 ]; then
                        let free=0
                        while [ $free -eq 0 ]; do
				let count=0
                                while [ $count -lt $cpu_count ]; do
                                        kill -0 ${pid_array[$count]} 2> /dev/null
                                        if [ $? -ne 0 ]; then 
                                                pid_array[$count]=0
                                                let free=1
                                                break
                                        else
                                        	let count=count+1
					fi
                                done
                                sleep .1
                        done
                fi
        done
done
wait
trap SIGINT
