int array_from_string(char *, char[][MAX_FIELDNAME_LENGTH]);
int ipfind(char*,char*);
int empty(char*);
void add_field(char*,char*);
void add_concatenation(char*,char*);
int lookup(FILE*, char*,char*);
FILE * table(char*);
void draw_chain(char*, char*, char);
void build_target_list(char*);
char * last_fieldname(char*);
char * last_value(char*);
void dedupe(char*, char);
void add_label(char*, char*);
void add_composite(char*, char*);
int add_patterns_filep(char*);
int extract_field_values();
int find_field_defs();
int find_fieldname(char*);
int find_patterns_filep(char*);
int get_input_lines();
int hostname_to_ip(char * ,char*);
int match_pattern(char*, char*);
int match(char*, char*);
int match_substring(char*, char*);
int set_input_fieldnames();
int strpos(char*, char*);
void set_graphics(char*, char*);
void add_asn(char *);
void draw_path(char *);
void add_country(char *);
void add_quotes(char *);
void define_csv_tag(char*);
void define_input_fieldnames(char,char *);
void drop_rec();
void cleanup();
void draw_node(char*,char*);
void global_clean(char*);
void init_storage();
int import_eml(char *);
void received_ip();
void input_clean(char*);
void insert_new_field(char*, char*);
void extract_hrefs(char *);
void keep_rec();
void loop();
void add_attributes(char*, char*);
int remchars(char*, char*);
void remove_chars(char*, char*);
void replace_char(char,char, char*);
void remove_string(char*, char*);
void rename_field(char*,char*);
void set_input(char, char *);
void set_input_directory(char,char*);
void set_output(char *);
void setup();
void socketadd_asn(char *);
void socketadd_country(char *);
void urldecode(char *);
void write_csv_fields(char *);
